[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/v1/.well-known/ready"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
QUERY_DEFAULTS_LIMIT = "25"
AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED = "true"
PERSISTENCE_DATA_PATH = "/var/lib/weaviate"
DEFAULT_VECTORIZER_MODULE = "none"
ENABLE_MODULES = ""
CLUSTER_HOSTNAME = "node1"
ORIGIN = "*"
